from __future__ import annotations

from datetime import datetime, timezone
import fcntl
import json
import os
from pathlib import Path
import shutil
from typing import Any
import uuid

from . import __version__
from .state import atomic_write_json


def make_submission_id() -> str:
    return datetime.now().strftime("%Y%m%d-%H%M%S") + "-" + uuid.uuid4().hex[:8]


def submission_root(output_dir: Path) -> Path:
    return output_dir / ".hummel-submit" / "submissions"


def _literal_absolute(path: str | Path) -> Path:
    """Expand a path without resolving symlinks.

    This is intentional for virtual environments on Hummel: ``bin/python`` can
    be a symlink into /sw/env while sibling console scripts such as ``law`` live
    in the virtualenv's own bin directory.
    """
    value = Path(os.path.expandvars(os.path.expanduser(str(path))))
    return value if value.is_absolute() else Path.cwd() / value


def _law_executable(python_executable: Path) -> Path:
    sibling = python_executable.parent / "law"
    if sibling.is_file():
        return sibling
    discovered = shutil.which("law")
    if discovered:
        return _literal_absolute(discovered)
    raise RuntimeError(
        f"law executable not found next to submission Python {python_executable} and not found on PATH"
    )


def _write_law_bootstrap(
    path: Path,
    *,
    python_executable: Path,
    law_executable: Path,
) -> None:
    python_bin = python_executable.parent
    law_bin = law_executable.parent
    path_entries = [str(python_bin)]
    if law_bin != python_bin:
        path_entries.append(str(law_bin))

    virtual_env = os.environ.get("VIRTUAL_ENV", "")
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by hummel-submit.  This file is sourced by law_job.sh.",
        "# Keep host Python/law outside application containers and do not enable nounset here.",
    ]
    if virtual_env:
        lines.append(f"export VIRTUAL_ENV={virtual_env!r}")
    lines += [
        f"export PATH={':'.join(path_entries)!r}:$PATH",
        "export PYTHONNOUSERSITE=1",
        "unset PYTHONHOME",
        f"[[ -x {str(law_executable)!r} ]] || {{ echo 'ERROR: frozen law executable is missing' >&2; return 41; }}",
        f"printf '[humsub bootstrap] python=%s\\n' {str(python_executable)!r}",
        f"printf '[humsub bootstrap] law=%s\\n' {str(law_executable)!r}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    path.chmod(0o755)


def create_submission_spec(
    *,
    output_dir: Path,
    project_dir: Path,
    config: dict[str, Any],
    run_name: str,
    user_args: list[str],
    resubmit: bool,
    python_executable: str,
) -> tuple[dict[str, Any], Path]:
    submission_id = make_submission_id()
    sdir = submission_root(output_dir) / submission_id
    sdir.mkdir(parents=True, exist_ok=False)

    run_dir = output_dir / "runs" / run_name
    run_dir.mkdir(parents=True, exist_ok=False)
    (output_dir / "logs").mkdir(parents=True, exist_ok=True)

    law_dir = sdir / "law"
    (law_dir / "job-files").mkdir(parents=True, exist_ok=True)
    (law_dir / "control").mkdir(parents=True, exist_ok=True)

    # Preserve the submitted interpreter path literally; never realpath it.
    python_path = _literal_absolute(python_executable)
    if not python_path.exists():
        raise RuntimeError(f"submission Python does not exist: {python_path}")
    law_path = _law_executable(python_path)

    law_bootstrap = law_dir / "bootstrap.sh"
    _write_law_bootstrap(
        law_bootstrap,
        python_executable=python_path,
        law_executable=law_path,
    )

    data: dict[str, Any] = {
        "schema": 2,
        "package_version": __version__,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "submission_id": submission_id,
        "project_dir": str(project_dir),
        "output_dir": str(output_dir),
        "run_name": run_name,
        "run_dir": str(run_dir),
        "success_marker": str(run_dir / ".humsub-complete"),
        "law_dir": str(law_dir),
        "law_bootstrap": str(law_bootstrap),
        "law_executable": str(law_path),
        "config": config,
        "user_args": user_args,
        "resubmit": resubmit,
        "python_executable": str(python_path),
        "chain_ids": [],
    }
    path = sdir / "submission.json"
    atomic_write_json(path, data)
    return data, path


def load_submission_spec(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def append_submission_chain(path: Path, chain_id: str) -> dict[str, Any]:
    lock_path = path.parent / ".submission.lock"
    with lock_path.open("a+") as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        data = load_submission_spec(path)
        if chain_id not in data["chain_ids"]:
            data["chain_ids"].append(chain_id)
        atomic_write_json(path, data)
        fcntl.flock(lock.fileno(), fcntl.LOCK_UN)
    return data
